// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAktQLlzrDNXr5ZkB6_TaKWxMzgh0689Ac',
    appId: '1:752491876759:web:3c9265be5ee740baecf4d2',
    messagingSenderId: '752491876759',
    projectId: 'vain-restaurantxy',
    authDomain: 'vain-restaurantxy.firebaseapp.com',
    storageBucket: 'vain-restaurantxy.appspot.com',
    measurementId: 'G-XDSYLRZEL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9DSKJolwjfS_UhyHvb9k2fl5EciUcB7Y',
    appId: '1:752491876759:android:8b9419337c3fa1a3ecf4d2',
    messagingSenderId: '752491876759',
    projectId: 'vain-restaurantxy',
    storageBucket: 'vain-restaurantxy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_7kYSYwo_fZix4jxd5Y83R2LQmb1_txg',
    appId: '1:752491876759:ios:98ed9756bc9ed6d3ecf4d2',
    messagingSenderId: '752491876759',
    projectId: 'vain-restaurantxy',
    storageBucket: 'vain-restaurantxy.appspot.com',
    iosClientId: '752491876759-tcvm1sr52ah5h8j8s494ng52j3otm8em.apps.googleusercontent.com',
    iosBundleId: 'com.example.dine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_7kYSYwo_fZix4jxd5Y83R2LQmb1_txg',
    appId: '1:752491876759:ios:4baae7708a62e337ecf4d2',
    messagingSenderId: '752491876759',
    projectId: 'vain-restaurantxy',
    storageBucket: 'vain-restaurantxy.appspot.com',
    iosClientId: '752491876759-6d2cc8s8qnestca5e8pbeacrr06c3bb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dine.RunnerTests',
  );
}
